login: &login
  access_key_id: <%= ENV['S3_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>

development:
  bucket_name: blogcms_development
  <<: *login
  distribution_domain: s3.amazonaws.com/blogcms_development

test:
  bucket_name: blogcms_test
  <<: *login
  distribution_domain: s3.amazonaws.com/blogcms_test

production:
  bucket_name: blogcms_production
  <<: *login
  distribution_domain: s3.amazonaws.com/blogcms_production
