login: &login
  username: <%= ENV['RACKSPACE_USERNAME'] %>
  api_key: <%= ENV['RACKSPACE_KEY'] %>

development:
  container_name: blogcms_development
  <<: *login 

test:
  container_name: blogcms_test
  <<: *login 

production:
  container_name: blogcms_production
  <<: *login 
